apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-obkepkpb
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-obkepkpb:a00e5d32f2ca5c0816dbdb4bb611f3c6f1e3de54@sha256:fd601cc09794434bf5ac6833d0f3e2e39aba657b271c09af4f4c495cf93e9cf2
        name: container-image  
